[[redirects]]
  from = "/politicas"
  to = "/politicas.html"
  status = 200

[[redirects]]
  from = "/politicas-devoluciones"
  to = "/politicas-devoluciones.html"
  status = 200

[[redirects]]
  from = "/politicas-cancelacion"
  to = "/politicas-cancelacion.html"
  status = 200

[[redirects]]
  from = "/politicas-envios"
  to = "/politicas-envios.html"
  status = 200

[[redirects]]
  from = "/politicas-privacidad"
  to = "/politicas-privacidad.html"
  status = 200

[[redirects]]
  from = "/politicas-tallas"
  to = "/politicas-tallas.html"
  status = 200

[[redirects]]
  from = "/politicas-produccion"
  to = "/politicas-produccion.html"
  status = 200
